### ISSUE TITLE
Errors in JSONStream.parse do not bubble up the stream

### ISSUE THREAD

**Issue by johnhaley81** [fergiemcdowall/search-index-replicator#1]
If there is an error in `JSONStream.parse` that error will be swallowed unless you attach an `.on('error', callback)` to that specific stream that is returned. So if you replicate an index and it contains an invalid character the callback is never called and you don't know what happened.

The line in question is: https://github.com/fergiemcdowall/search-index-replicator/blob/master/replicator.js#L18

I have a fix for this that I can PR if you'd like.

**Comment by fergiemcdowall** [comment]
Good point, yes please send over the PR

**Comment by johnhaley81** [comment]
PR was merged so I'll close this out.
